version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  nodejs:
    container_name: nodejs
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./server:/app:ro
      - /app/node_modules
    restart: always
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    restart: always
    command: npm run dev

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-cache:/data
    restart: always

volumes:
  mongo-db:
  redis-cache:
